apiVersion: apps/v1
kind: Deployment
metadata:
  name: ing2-deployment
  namespace: integrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ing2
  template:
    metadata:
      labels:
        app: ing2
    spec:
      containers:
        - name: ing2
          image: nerdysrisha/ing2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ing2-service
  namespace: integrations
spec:
  type: ClusterIP
  selector:
    app: ing2
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082