apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld-deployment
  namespace: integrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hworld
  template:
    metadata:
      labels:
        app: hworld
    spec:
      containers:
        - name: hworld
          image: nerdysrisha/hworld:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hworld-service
  namespace: integrations
spec:
  type: NodePort
  selector:
    app: hworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
